version: '3.8'

services:
  webapi:
    image: RestApi
    build: .
    ports:
      - "5159:80"
    environment:
      - ASPNETCORE_URLS=http://+:80  # Ensure the app listens on all network interfaces inside the container

